# Generated by Django 5.1.1 on 2024-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique="True")),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("sub_category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="product_images/")),
                ("product_condition", models.CharField(max_length=50)),
                (
                    "product_age",
                    models.IntegerField(help_text="Product age in months or years"),
                ),
                ("size", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
            ],
        ),
    ]
