# Generated by Django 4.2.5 on 2024-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_rename_color_product_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, help_text='base price by owner'),
            preserve_default=False,
        ),
    ]
